import bag from './assets/bag.jpeg'
import bag1 from './assets/bag1.jpeg'
import bag2 from './assets/bag2.jpeg'
import bag3 from './assets/bag3.jpeg'

export const ITEMS = [
  {
    id: 0,
    title: 'ASOS DESIGN bag with detachable strap',
    brand: 'VS',
    price: 100.00,
    description: 'ASOS DESIGN rose gold zipped compartment tote bag with detachable strap',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
  },
  {
    id: 1,
    title: 'Skirt',
    brand: 'Bershka',
    price: 30.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
  },
  {
    id: 2,
    title: 'Top',
    brand: 'Asos',
    price: 149.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
  },
  {
    id: 3,
    title: 'Top',
    brand: 'Asos',
    price: 90.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
  },
  {
    id: 4,
    title: 'Top',
    brand: 'Asos',
    price: 20.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
  },
  {
    id: 5,
    title: 'Top',
    brand: 'Asos',
    price: 10.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
  },
  {
    id: 6,
    title: 'Top',
    brand: 'Asos',
    price: 13.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
  },
  {
    id: 7,
    title: 'Top',
    brand: 'Asos',
    price: 67.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
  },
  {
    id: 8,
    title: 'Top',
    brand: 'Asos',
    price: 55.90,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
  },
  {
    id: 9,
    title: 'Top',
    brand: 'Asos',
    price: 44.43,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
  },
  {
    id: 10,
    title: 'Top',
    brand: 'Asos',
    price: 12.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
  },
  {
    id: 11,
    title: 'Top',
    brand: 'Asos',
    price: 34,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
  },
  {
    id: 12,
    title: 'Top',
    brand: 'Asos',
    price: 35.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
  },
  {
    id: 13,
    title: 'Top',
    brand: 'Asos',
    price: 24.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
  },
  {
    id: 14,
    title: 'Top',
    brand: 'Asos',
    price: 19.50,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
  },

]
