import bag from './assets/bag.jpeg'
import bag1 from './assets/bag1.jpeg'
import bag2 from './assets/bag2.jpeg'
import bag3 from './assets/bag3.jpeg'

export const ITEMS = [
  {
    id: 0,
    title: 'ASOS DESIGN bag with detachable strap',
    brand: 'VS',
    price: 100.00,
    description: 'ASOS DESIGN rose gold zipped compartment tote bag with detachable strap',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 1,
    title: 'In The Style x Billie Faiers roll neck knitted dress with belt in pink',
    brand: 'Bershka',
    price: 30.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
    category: 'skirts',
  },
  {
    id: 2,
    title: 'Monki Nonna cotton ribbed square neck top in black',
    brand: 'Monki Nonna',
    price: 149.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
    category: 'shoes',
  },
  {
    id: 3,
    title: 'adidas Originals mesh logo co ord in blue',
    brand: 'Adidas',
    price: 90.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 4,
    title: 'Daisy Street Plus mom jeans in bleach denim',
    brand: 'Daisy Street',
    price: 20.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 5,
    title: 'Nike Air Force 1 Shadow in pale blue and mint multi',
    brand: 'Nike',
    price: 10.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 6,
    title: 'ASOS DESIGN denim co-ord in sage cord',
    brand: 'Asos',
    price: 13.00,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
    quantity: 0,
  },
  {
    id: 7,
    title: 'COLLUSION reverse loopback tie dye swirl print hoodie',
    brand: 'COLLUSION',
    price: 67.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 8,
    title: 'South Beach exaggerated wire bikini set in gold metallic',
    brand: 'South Beach',
    price: 55.90,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 9,
    title: 'Kaz Bands headband with twist knot in red satin',
    brand: 'Kaz Bands',
    price: 44.43,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 10,
    title: 'New Look waist enhance mom jeans in mid blue',
    brand: 'New Look',
    price: 12.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 11,
    title: 'Top',
    brand: 'Asos',
    price: 34,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 12,
    title: 'Top',
    brand: 'Asos',
    price: 35.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: false,
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 13,
    title: 'Top',
    brand: 'Asos',
    price: 24.99,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
    category: 'accessories',
  },
  {
    id: 14,
    title: 'Top',
    brand: 'Asos',
    price: 19.50,
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
    liked: true,
    quantity: 0,
    category: 'accessories',
  },

]
