import bag from './assets/bag.jpeg'
import bag1 from './assets/bag1.jpeg'
import bag2 from './assets/bag2.jpeg'
import bag3 from './assets/bag3.jpeg'

export const WISHES = [
  {
    id: 0,
    title: 'ASOS DESIGN bag with detachable strap',
    brand: 'VS',
    price: '$100.00',
    description: 'ASOS DESIGN rose gold zipped compartment tote bag with detachable strap',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
  },
  {
    id: 1,
    title: 'Skirt',
    brand: 'Bershka',
    price: '$30',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 2,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
  },
  {
    id: 3,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
  },
  {
    id: 4,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
  },
  {
    id: 5,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
  },
  {
    id: 6,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    liked: true,
    color: 'black',
  },
  {
    id: 7,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 8,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 9,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 10,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 11,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 12,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 13,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },
  {
    id: 14,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    images: [
      bag,
      bag1,
      bag2,
      bag3,
    ],
    color: 'black',
  },

]
