
export const WISHES = [
  {
    id: 0,
    title: 'Backpack',
    brand: 'VS',
    price: '$100',
    description: 'ASOS DESIGN rose gold zipped compartment tote bag with detachable strap',
    image: './assets/bag.jpeg',
    rating: '5',
  },
  {
    id: 1,
    title: 'Skirt',
    brand: 'Bershka',
    price: '$30',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 2,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 3,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 4,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 5,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 6,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 7,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 8,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 9,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 10,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 11,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 12,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 13,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },
  {
    id: 14,
    title: 'Top',
    brand: 'Asos',
    price: '$20',
    description: 'nice',
    image: './assets/bag.jpeg',
  },

]
